<?php

use App\Controllers\API\AdminOps;
use App\Controllers\API\AuthController;
use App\Controllers\API\LogoutController;
use App\Controllers\API\SessionController;
use App\Controllers\API\DomainRegistration;
use App\Controllers\API\AddToCart;
use App\Controllers\API\CartItems;
use App\Controllers\API\CallFlutter;
use App\Controllers\API\ChatsController;
use App\Controllers\API\UserProducts;
use App\Controllers\API\AdminDashboard;
use App\Controllers\API\PanelEmailOperations;
use App\Controllers\API\StaticController;

$router->get('/api/session', [SessionController::class, 'userSession']);
$router->get('/api/session-data', [SessionController::class, 'userData']);
$router->get('/api/session-address', [SessionController::class, 'userAddress']);
$router->get('/api/acct-bal', [SessionController::class, 'acctBal']);
$router->post('/api/get-websites', [SessionController::class, 'webList']);
$router->post('/api/get-websites-all', [SessionController::class, 'webListAll']);
$router->post('/api/get-single-website', [SessionController::class, 'getSingleWeb']);
$router->post('/api/register', [AuthController::class, 'register']);
$router->post('/api/login', [AuthController::class, 'login']);
$router->post('/api/forget-password', [AuthController::class, 'forgetPassword']);
$router->post('/api/verify-reset-code', [AuthController::class, 'passResetCode']);
$router->post('/api/update-password', [AuthController::class, 'updatePassword']);
$router->post('/api/admin-login', [AuthController::class, 'adminLogin']);
$router->post('/api/update-naira', [AuthController::class, 'currency']);
$router->get('/api/get-naira', [AuthController::class, 'getNaira']);
$router->get('/api/get-user-location', [AuthController::class, 'getLocation']);
$router->post('/api/add-website', [AuthController::class, 'addWeb']);
$router->post('/api/update-email', [AuthController::class, 'updateEmail']);
$router->post('/api/update-address', [AuthController::class, 'updateAddress']);
$router->get('/api/logout', [LogoutController::class, 'userLogout']);
$router->post('/api/domain-search', [DomainRegistration::class, 'domainSearch']);
$router->post('/api/single-search', [DomainRegistration::class, 'singleSearch']);
$router->post('/api/domain-check', [DomainRegistration::class, 'existingCheck']);
$router->get('/api/get-domain-prices', [DomainRegistration::class, 'getDomainPrices']);
$router->post('/api/update-dns', [DomainRegistration::class, 'updateDns']);
$router->post('/api/update-host', [DomainRegistration::class, 'updateHost']);
$router->post('/api/get-host', [DomainRegistration::class, 'getHost']);
$router->post('/api/get-domain-details', [DomainRegistration::class, 'getDomainDetails']);
$router->post('/api/get-domain-lock-status', [DomainRegistration::class, 'getDomainLockStatus']);
$router->post('/api/change-domain-ownership', [DomainRegistration::class, 'changeOwnership']);
$router->post('/api/add-domain-manager', [DomainRegistration::class, 'domainManager']);
$router->post('/api/unlock-domain', [DomainRegistration::class, 'unlockDomain']);
$router->post('/api/add-to-cart', [AddToCart::class, 'addDomain']);
$router->post('/api/transfer-to-cart', [AddToCart::class, 'tranferDomain']);
$router->post('/api/add-to-cart-hosting', [AddToCart::class, 'addHosting']);
$router->post('/api/add-to-cart-ssl', [AddToCart::class, 'addSSL']);
$router->post('/api/add-to-cart-email', [AddToCart::class, 'addEmail']);
$router->post('/api/add-website-to-cart', [AddToCart::class, 'addWebsite']);
$router->post('/api/add-custom-website-to-cart', [AddToCart::class, 'addCustomWebsite']);
$router->get('/api/cart-items', [CartItems::class, 'cartItems']);
$router->get('/api/cart-total-price', [CartItems::class, 'cartTotal']);
$router->get('/api/cart-domain', [CartItems::class, 'cartDomain']);
$router->post('/api/empty-user-cart', [CartItems::class, 'clearAllItems']);
$router->post('/api/remove-item', [CartItems::class, 'removeItem']);
$router->get('/api/cart-session', [CartItems::class, 'cartSession']);
$router->post('/api/payment-success', [CallFlutter::class, 'paymentSuccessful']);
$router->post('/api/topup-success', [CallFlutter::class, 'topupSuccessful']);
$router->get('/api/run-test', [CallFlutter::class, 'adminCreateHosting']);
$router->post('/api/chat-registration', [ChatsController::class, 'createChatUser']);
$router->post('/api/add-chat', [ChatsController::class, 'addChat']);
$router->get('/api/get-chats', [ChatsController::class, 'getChats']);
$router->post('/api/consult', [ChatsController::class, 'consult']);
$router->post('/api/send-ticket', [ChatsController::class, 'openTicket']);
$router->get('/api/user-tickets', [ChatsController::class, 'getTickets']);
$router->get('/api/get-dashboard', [UserProducts::class, 'getDashboardProducts']);
$router->post('/api/get-user-domain-products', [UserProducts::class, 'getDomainProducts']);
$router->get('/api/get-expiring', [UserProducts::class, 'expiringProduct']);
$router->get('/api/user-domain', [UserProducts::class, 'domainList']);
$router->get('/api/user-hosting', [UserProducts::class, 'hostingList']);
$router->get('/api/user-email', [UserProducts::class, 'emailList']);
$router->get('/api/user-ssl', [UserProducts::class, 'sslList']);
$router->get('/api/user-app', [UserProducts::class, 'appList']);
$router->get('/api/get-iruap-domain', [UserProducts::class, 'getIruapDomain']);
$router->get('/api/get-signups', [AdminDashboard::class, 'signUps']);
$router->get('/api/get-active-users', [AdminDashboard::class, 'activeUsers']);
$router->get('/api/get-total-sales', [AdminDashboard::class, 'getTotalSalesNum']);
$router->get('/api/get-web-sales', [AdminDashboard::class, 'getTotalWebSalesNum']);
$router->post('/api/add-blog', [AdminOps::class, 'addBlogs']);
$router->get('/api/admin-get-chats', [AdminOps::class, 'getChats']);
$router->get('/api/admin-get-visitor-chats', [AdminOps::class, 'getVisitorChats']);
$router->get('/api/get-admin-chat', [AdminOps::class, 'getChat']);
$router->post('/api/send-admin-chat', [AdminOps::class, 'sendChat']);
$router->post('/api/add-tld', [AdminOps::class, 'addTld']);
$router->post('/api/update-admin-chat', [AdminOps::class, 'updateChats']);
$router->get('/api/run-migrations', [AdminOps::class, 'updateMigrations']);
$router->get('/api/get-blogs', [StaticController::class, 'getBlogs']);
$router->get('/api/get-recent-blogs', [StaticController::class, 'recentBlogs']);
$router->get('/api/get-todays-blogs', [StaticController::class, 'todayBlogs']);
$router->post('/api/get-single-blogs', [StaticController::class, 'singleBlog']);
$router->post('/api/get-related-blogs', [StaticController::class, 'relatedBlog']);
$router->post('/api/get-other-blogs', [StaticController::class, 'otherBlog']);
$router->get('/api/get-blog/{slug}', [StaticController::class, 'getBlogBySlug']);

$router->get('/api/expiring-products', [AdminDashboard::class, 'expiringProducts']);
$router->get('/api/expiring-message', [AdminDashboard::class, 'expiringMessage']);

$router->post('/api/panel-login', [AuthController::class, 'panelUser']);
$router->get('/api/auto-login', [AuthController::class, 'panelAutoLogin']);
$router->get('/api/check-panel-session', [SessionController::class, 'checkPanelUser']);
$router->post('/api/create-email-db', [PanelEmailOperations::class, 'createEmailDb']);
$router->get('/api/open-user-database', [PanelEmailOperations::class, 'openUserDatabase']);