<?php

use App\Controllers\API\AuthController;
use App\Controllers\API\LogoutController;
use App\Controllers\API\SessionController;
use App\Controllers\API\DomainRegistration;
use App\Controllers\API\AddToCart;
use App\Controllers\API\CartItems;
use App\Controllers\API\CallFlutter;
use App\Controllers\API\ChatsController;
use App\Controllers\API\UserProducts;
use App\Controllers\API\AdminDashboard;


$router->get('/api/session', [SessionController::class, 'userSession']);
$router->get('/api/session-data', [SessionController::class, 'userData']);
$router->get('/api/session-address', [SessionController::class, 'userAddress']);
$router->get('/api/acct-bal', [SessionController::class, 'acctBal']);
$router->post('/api/get-websites', [SessionController::class, 'webList']);
$router->post('/api/get-single-website', [SessionController::class, 'getSingleWeb']);
$router->post('/api/register', [AuthController::class, 'register']);
$router->post('/api/login', [AuthController::class, 'login']);
$router->post('/api/admin-login', [AuthController::class, 'adminLogin']);
$router->post('/api/update-naira', [AuthController::class, 'currency']);
$router->get('/api/get-naira', [AuthController::class, 'getNaira']);
$router->post('/api/add-website', [AuthController::class, 'addWeb']);
$router->post('/api/update-email', [AuthController::class, 'updateEmail']);
$router->post('/api/update-address', [AuthController::class, 'updateAddress']);
$router->post('/api/logout', [LogoutController::class, 'userLogout']);
$router->post('/api/domain-search', [DomainRegistration::class, 'domainSearch']);
$router->post('/api/single-search', [DomainRegistration::class, 'singleSearch']);
$router->post('/api/domain-check', [DomainRegistration::class, 'existingCheck']);
$router->get('/api/get-domain-prices', [DomainRegistration::class, 'getDomainPrices']);
$router->post('/api/add-to-cart', [AddToCart::class, 'addDomain']);
$router->post('/api/transfer-to-cart', [AddToCart::class, 'tranferDomain']);
$router->post('/api/add-to-cart-hosting', [AddToCart::class, 'addHosting']);
$router->post('/api/add-to-cart-ssl', [AddToCart::class, 'addSSL']);
$router->post('/api/add-website-to-cart', [AddToCart::class, 'addWebsite']);
$router->get('/api/cart-items', [CartItems::class, 'cartItems']);
$router->get('/api/cart-total-price', [CartItems::class, 'cartTotal']);
$router->get('/api/cart-domain', [CartItems::class, 'cartDomain']);
$router->post('/api/empty-user-cart', [CartItems::class, 'clearAllItems']);
$router->post('/api/remove-item', [CartItems::class, 'removeItem']);
$router->get('/api/cart-session', [CartItems::class, 'cartSession']);
$router->post('/api/payment-success', [CallFlutter::class, 'paymentSuccessful']);
$router->post('/api/topup-success', [CallFlutter::class, 'topupSuccessful']);
$router->post('/api/chat-registration', [ChatsController::class, 'createChatUser']);
$router->post('/api/add-chat', [ChatsController::class, 'addChat']);
$router->get('/api/get-chats', [ChatsController::class, 'getChats']);
$router->get('/api/get-dashboard', [UserProducts::class, 'getDashboardProducts']);
$router->get('/api/get-expiring', [UserProducts::class, 'expiringProduct']);
$router->get('/api/user-domain', [UserProducts::class, 'domainList']);
$router->get('/api/user-hosting', [UserProducts::class, 'hostingList']);
$router->get('/api/user-email', [UserProducts::class, 'emailList']);
$router->get('/api/user-ssl', [UserProducts::class, 'sslList']);
$router->get('/api/user-app', [UserProducts::class, 'appList']);
$router->get('/api/get-signups', [AdminDashboard::class, 'signUps']);
$router->get('/api/get-active-users', [AdminDashboard::class, 'activeUsers']);
$router->get('/api/get-total-sales', [AdminDashboard::class, 'getTotalSalesNum']);
$router->get('/api/get-web-sales', [AdminDashboard::class, 'getTotalWebSalesNum']);
